export const pipeSharedContent = {
  materialGroups: [
    ["Stainless Steel", "ASTM A312 TP304, TP304L, TP316, TP316L, TP310S, TP317L, TP321, TP347, TP347H and TP904L"],
    ["Duplex Stainless Steel", "UNS S31803 and UNS S32205 (2205)"],
    ["Super Duplex Stainless Steel", "UNS S32750 (2507) and UNS S32760"],
    ["Nickel Alloys", "Inconel 600, 601, 625 and X-750; Incoloy 800, 800H, 800HT and 825; Monel 400 and K500; Hastelloy C22 and C276; Alloy 20 and Alloy 28"],
    ["Titanium", "Grade 2 and Grade 5"],
    ["Copper Nickel", "C70600 (90/10) and C71500 (70/30)"],
  ],
  standardGroups: [
    {
      title: "Material standards",
      rows: [
        ["ASTM A312 / A312M", "Seamless and welded austenitic stainless steel pipe"],
        ["ASTM A358", "Electric-fusion-welded austenitic stainless pipe"],
        ["ASTM A778", "Welded, unannealed austenitic stainless pipe"],
        ["ASTM A790", "Seamless and welded ferritic-austenitic (duplex) stainless pipe"],
        ["ASTM A928", "Electric-fusion-welded duplex stainless pipe"],
        ["ASTM B444", "Nickel alloy (UNS N06625 / N06600) pipe and tube"],
        ["ASTM B622", "Nickel-alloy (Hastelloy-type) pipe"],
        ["ASTM B861", "Titanium and titanium-alloy seamless pipe"],
        ["ASTM B163", "Nickel-alloy seamless tube for condenser and heat exchanger service"],
      ],
    },
    {
      title: "Dimensional standards",
      rows: [
        ["ASME B36.10M", "Wrought steel pipe dimensions"],
        ["ASME B36.19M", "Stainless steel pipe dimensions"],
      ],
    },
    {
      title: "European standards",
      rows: [
        ["EN 10216-5", "Seamless stainless steel tubes for pressure purposes"],
        ["EN 10217-7", "Welded stainless steel tubes for pressure purposes"],
      ],
    },
  ],
  chemicalHeaders: ["Grade", "C", "Cr", "Ni", "Mo", "Other"],
  chemical: [
    ["304", "≤0.08", "18.0–20.0", "8.0–11.0", "—", "Mn ≤2.0, Si ≤1.0"],
    ["304L", "≤0.035", "18.0–20.0", "8.0–13.0", "—", "Mn ≤2.0, Si ≤1.0"],
    ["316", "≤0.08", "16.0–18.0", "10.0–14.0", "2.0–3.0", "Mn ≤2.0, Si ≤1.0"],
    ["316L", "≤0.035", "16.0–18.0", "10.0–14.0", "2.0–3.0", "Mn ≤2.0, Si ≤1.0"],
    ["310S", "≤0.08", "24.0–26.0", "19.0–22.0", "—", "Mn ≤2.0, Si ≤1.5"],
    ["317L", "≤0.035", "18.0–20.0", "11.0–15.0", "3.0–4.0", "Mn ≤2.0, Si ≤1.0"],
    ["321", "≤0.08", "17.0–19.0", "9.0–12.0", "—", "Ti: 5×C min–0.70"],
    ["347", "≤0.08", "17.0–19.0", "9.0–13.0", "—", "Nb+Ta: 10×C min–1.00"],
    ["347H", "0.04–0.10", "17.0–20.0", "9.0–13.0", "—", "Nb+Ta: 8×C min–1.00"],
    ["904L", "≤0.02", "19.0–23.0", "23.0–28.0", "4.0–5.0", "Cu: 1.0–2.0"],
    ["2205 (Duplex)", "≤0.03", "22.0–23.0", "4.5–6.5", "3.0–3.5", "N: 0.14–0.20"],
    ["2507 (Super Duplex)", "≤0.03", "24.0–26.0", "6.0–8.0", "3.0–5.0", "N: 0.24–0.32"],
    ["Inconel 625", "≤0.10", "20.0–23.0", "Balance (≥58)", "8.0–10.0", "Nb+Ta: 3.15–4.15"],
    ["Incoloy 825", "≤0.05", "19.5–23.5", "38.0–46.0", "2.5–3.5", "Cu: 1.5–3.0"],
    ["Hastelloy C276", "≤0.01", "14.5–16.5", "Balance (≥57)", "15.0–17.0", "W: 3.0–4.5, Fe: 4.0–7.0"],
  ],
  mechanicalHeaders: ["Grade", "Tensile strength (MPa, min)", "Yield strength (MPa, min)", "Elongation (%, min)", "Density (g/cm³)", "Melting range (°C)"],
  mechanical: [
    ["304", "515", "205", "35", "8.00", "1400–1450"],
    ["304L", "485", "170", "35", "8.00", "1400–1450"],
    ["316", "515", "205", "35", "8.00", "1375–1400"],
    ["316L", "485", "170", "35", "8.00", "1375–1400"],
    ["310S", "515", "205", "35", "7.98", "1400–1450"],
    ["317L", "485", "170", "35", "8.00", "1375–1400"],
    ["321", "515", "205", "35", "8.00", "1400–1425"],
    ["347", "515", "205", "35", "8.03", "1400–1425"],
    ["347H", "515", "205", "35", "8.03", "1400–1425"],
    ["904L", "490", "220", "35", "8.00", "1320–1390"],
    ["2205 (Duplex)", "620", "450", "25", "7.80", "1350–1400"],
    ["2507 (Super Duplex)", "795", "550", "15", "7.80", "1350"],
    ["Inconel 625", "827", "414", "30", "8.44", "1290–1350"],
    ["Incoloy 825", "586", "241", "30", "8.14", "1370–1400"],
    ["Hastelloy C276", "690", "283", "40", "8.89", "1325–1370"],
  ],
  inspectionDetails: [
    ["PMI (Positive Material Identification)", "Confirms alloy chemistry matches the ordered grade."],
    ["Hydro Test", "Hydrostatic pressure test to the specified test pressure and hold time."],
    ["UT (Ultrasonic Testing)", "Detects internal discontinuities without damaging the pipe."],
    ["ET (Eddy Current Testing)", "Surface and near-surface flaw detection, common on tube products."],
    ["RT (Radiographic Testing)", "X-ray/gamma examination of welds or wall for internal defects."],
    ["IGC Test", "Intergranular corrosion test (e.g. ASTM A262) for weld-sensitised austenitic grades."],
    ["Flattening Test", "Confirms ductility of welded pipe by flattening a sample section."],
    ["Flaring Test", "Confirms ductility/formability of tube ends by flaring a sample."],
    ["Hardness Test", "Verifies hardness is within the limit specified for the grade/condition."],
    ["Third-Party Inspection", "Witnessing/certification by agencies such as BV, SGS, TUV or Lloyd's."],
    ["EN 10204 3.1 Certification", "Mill test certificate validated by the manufacturer's own inspection department."],
  ],
  inspection: [
    "Positive Material Identification and chemistry verification",
    "Hydrostatic pressure testing",
    "Ultrasonic, eddy-current and radiographic testing as specified",
    "Intergranular corrosion, flattening, flaring and hardness testing",
    "Third-party inspection and EN 10204 certification support",
  ],
  industries: ["EPC Contractors", "OEMs", "Fabricators", "Heat Exchanger Manufacturers", "Boiler Manufacturers", "Shipbuilding", "Infrastructure Projects", "Process Plants"],
  packaging: ["Bundle Packing", "Wooden Boxes", "Export Crates", "Plastic End Caps", "Waterproof Wrapping", "Heat Number Identification", "Barcode (Optional)", "Customer Marking"],
  whyNesco: [
    ["Wide Product Portfolio", "Pipes, tubes, flanges, fittings, bars, sheets/plates and fasteners from one supplier."],
    ["Multi-Material Supply", "Stainless, duplex, super duplex, nickel alloy, titanium and copper-nickel under one enquiry."],
    ["Mill Test Certificates", "EN 10204 3.1 as standard, 3.2 with third-party witness where applicable."],
    ["Third-Party Inspection Support", "Coordination with BV, SGS, TUV, Lloyd's and other agencies on request."],
    ["Reliable Sourcing", "Established mill and stockist relationships for consistent availability."],
    ["Fast RFQ Response", "Enquiries reviewed against the complete technical requirement, not just price."],
    ["Project Supply Expertise", "Experience handling project packages alongside routine maintenance orders."],
    ["Export Documentation Support", "Assistance with the paperwork needed for international shipment."],
    ["Custom Cutting & End Preparation", "Subject to size, grade and quantity availability."],
    ["One-Stop Solution", "A single point of contact for industrial piping product requirements."],
  ],
  faqs: [
    ["What is the difference between Seamless and Welded pipes?", "Seamless pipe is pierced from a solid billet and has no weld seam, giving uniform strength in all directions; welded pipe is formed from strip/plate and joined along a longitudinal seam, which allows a wider size range at a generally lower cost."],
    ["When is EFW pipe used instead of standard Welded pipe?", "EFW pipe is used when the required diameter or wall thickness exceeds what standard coil-fed welded production can practically achieve — typically large process headers and heavy-wall pressure piping, where the pipe is rolled from individual plate rather than coil."],
    ["Which grade should I select?", "Grade selection depends on the fluid handled, chloride content, pressure, temperature, fabrication method and the applicable project or code requirement. NESCO can quote the grade requested; final material selection remains with the project engineer."],
    ["Do you provide EN 10204 3.1 certificates?", "Yes, EN 10204 3.1 mill test certificates are provided as standard; 3.2 certificates with third-party witnessing can be arranged on request."],
    ["Can you supply cut lengths?", "Cut lengths are available subject to grade, size, quantity and manufacturing route — include the required length and tolerance in your enquiry."],
    ["What standards do you follow?", "Primarily ASTM/ASME material and dimensional standards, with EN equivalents available where specified. See the Manufacturing Standards section for the full list."],
    ["Do you export internationally?", "Yes, export packing and shipping documentation support are part of NESCO's standard service."],
    ["Can third-party inspection be arranged?", "Yes, inspection through agencies such as BV, SGS, TUV or Lloyd's can be coordinated when stated in the purchase order."],
    ["What is the minimum order quantity?", "This depends on the grade, size and whether the item is ex-stock or made-to-order; please share your requirement for a specific answer."],
    ["Do you stock all grades?", "Common grades are typically held ex-stock; less common alloys, large sizes and EFW pipe are generally sourced from the mill on a made-to-order basis."],
    ["How can I request a quotation?", "Use the Request for Quotation form on this page, or send your specification, drawing or bill of materials by email."],
    ["What end preparations are available?", "Plain end is standard on seamless and welded pipe; bevelled ends to ASME B16.25 (or the project WPS for EFW) and threaded ends are available subject to size and specification."],
    ["Can NESCO supply Positive Material Identification (PMI) reports?", "Yes, PMI testing can be arranged and reported alongside the mill test certificate when requested at enquiry stage."],
  ],
  relatedProductTitles: ["Seamless Tubes", "Welded Tubes", "Weld Neck Flanges", "Elbows", "Sheets", "Plates", "Round Bars", "Bolts"],
} as const;

export const pipePageContent = {
  "Seamless Pipes": {
    displayTitle: "Stainless Steel Seamless Pipes",
    tagline: "Reliable Industrial Piping Solutions for Oil & Gas, Petrochemical, Power, Marine & Process Industries.",
    overviewContent: [
      "NESCO Pipe & Tubes supplies stainless steel seamless pipes for process, pressure and structural piping systems across the oil & gas, petrochemical, power, marine and general process industries. Seamless pipe is manufactured without a longitudinal weld seam: a solid steel billet is pierced or extruded into a hollow shell, then hot-finished and, where required, cold drawn to the specified outside diameter and wall thickness, followed by solution heat treatment, straightening and final inspection. The absence of a weld seam gives the pipe a uniform circumferential structure, which is a key reason it is preferred for high-pressure, high-temperature and critical-service applications where weld-related weak points must be avoided.",
      "The main advantages of seamless construction are consistent wall thickness, high pressure-holding capability, strong performance across a wide temperature range, and reliable behaviour under cyclic or dynamic loading. These pipes are typically specified in process lines, refineries, chemical and petrochemical plants, power generation and steam systems, marine and offshore piping, and general industrial fabrication, wherever the specifying engineer needs a proven, code-recognised product with a long service history.",
      "Industries prefer seamless stainless pipe because it combines corrosion resistance with dependable mechanical performance and is backed by long-standing ASTM and ASME specifications that most purchasing and engineering standards already recognise. NESCO Pipe & Tubes supports this with a wide grade range, specification-led order review, mill test certificate support, and inspection coordination including PMI and third-party witnessing — making NESCO a practical single-point source for both routine maintenance orders and larger project packages.",
    ],
    keyFeatures: ["Excellent Corrosion Resistance", "High Pressure Capability", "High Temperature Performance", "Superior Mechanical Strength", "Excellent Weldability", "Long Service Life", "Low Maintenance", "Wide Material Availability"],
    specificationReferences: ["ASTM A312 / ASME SA312 material specification", "ASME B36.19M dimensional specification", "ASME B16.25 bevelled-end preparation", "Project-specific supplementary inspection requirements"],
    productSpecifications: [
      ["Product Standard", "ASTM A312 / ASME SA312 (material); ASME B36.19M (dimensions)"],
      ["Manufacturing Type", "Seamless (hot pierced / extruded, cold drawn where required)"],
      ["Size Range", "1/8\" NPS to 24\" NPS (larger sizes on enquiry)"],
      ["Wall Thickness", "Schedule 5S to Schedule XXS"],
      ["Length", "Single Random (5–7 m), Double Random (11–13 m), or Fixed Cut Length"],
      ["Ends", "Plain End (PE); Bevelled End (BE) to ASME B16.25; Threaded on request"],
      ["Surface Finish", "Annealed & Pickled (standard); Bright Annealed or Polished on request"],
      ["Marking", "Standard mill marking; custom marking on request"],
      ["Packaging", "Export-worthy bundling, end protection and crating"],
    ],
    dimensionsNote: "Representative NPS / schedule chart. A complete chart can be requested through the product enquiry form.",
    dimensionHeaders: ["NPS", "OD (mm)", "Wall thickness (mm) — Sch 40/80/160", "Schedule"],
    dimensions: [
      ["1/2\"", "21.3", "2.11 / 2.77 / 3.73", "40 / 80 / 160"],
      ["1\"", "33.4", "3.38 / 4.55 / 6.35", "40 / 80 / 160"],
      ["2\"", "60.3", "3.91 / 5.54 / 8.74", "40 / 80 / 160"],
      ["4\"", "114.3", "6.02 / 8.56 / 13.49", "40 / 80 / 160"],
      ["6\"", "168.3", "7.11 / 10.97 / 18.26", "40 / 80 / 160"],
      ["8\"", "219.1", "8.18 / 12.70 / 22.23", "40 / 80 / 160"],
    ],
    manufacturing: [
      "Solid stainless steel billet selected and verified by heat and chemistry.",
      "Billet is rotary-pierced or extruded into a hollow shell without a weld seam.",
      "Solution annealing restores corrosion resistance and required grain structure.",
      "Hot finishing and, where specified, cold drawing bring the pipe to final OD and wall.",
      "Pipe is straightened to the tolerance required by the governing dimensional standard.",
      "Surface is pickled and passivated to remove scale and restore the passive oxide layer.",
      "Dimensional, visual, hydrostatic and any specified NDT checks are carried out.",
      "Heat-wise bundling, end protection and export-worthy packing for dispatch.",
    ],
  },
  "Welded Pipes": {
    displayTitle: "Stainless Steel Welded Pipes",
    tagline: "Broad Size Range, Reliable Welded Piping for Process, Utility & Industrial Applications.",
    overviewContent: [
      "NESCO Pipe & Tubes supplies welded stainless steel and duplex pipes for process, utility and general industrial piping systems where a broad size range and dimensional flexibility are needed alongside proven material performance. Welded pipe is manufactured from strip or plate: the material is formed into a cylindrical shape and joined along a longitudinal seam using a qualified welding procedure, after which the pipe is heat treated, sized, straightened and inspected to the requirements of the governing specification.",
      "Welded construction allows a wider practical range of diameters and wall thicknesses than seamless production, and is generally more cost-efficient for large-diameter and thin-to-medium wall requirements. Because the longitudinal seam is a defined, inspectable feature, it can be radiographically or ultrasonically examined along its full length, giving purchasers a documented, traceable quality record for the weld itself, in addition to the parent material certification.",
      "Industries choose welded pipe from NESCO Pipe & Tubes because it combines a wide grade and size range with documented weld inspection, dimensional consistency and mill certification support. NESCO reviews each welded pipe enquiry against material grade, standard, size, wall thickness, length, end preparation and testing requirement, and can coordinate third-party inspection where the project calls for it — making welded pipe a dependable, cost-effective option across structural, utility and process applications.",
    ],
    keyFeatures: ["Wide Diameter & Wall-Thickness Range", "Cost-Efficient for Large Orders", "Inspectable Longitudinal Seam", "Good Corrosion Resistance", "Suitable for Structural & Process Duty", "Available in Multiple Surface Finishes", "Fast Lead Times on Common Sizes", "Wide Material Availability"],
    specificationReferences: ["ASTM A312, A358 and A928 material specifications", "ASME B36.19M dimensional specification", "Qualified ERW or EFW manufacturing routes", "Project-specific seam examination requirements"],
    productSpecifications: [
      ["Product Standard", "ASTM A312 / A358 / A928 (material); ASME B36.19M (dimensions)"],
      ["Manufacturing Type", "Welded — longitudinal seam (ERW or EFW route as applicable to size)"],
      ["Size Range", "1/2\" NPS to 48\" NPS (project sizes on enquiry)"],
      ["Wall Thickness", "Schedule 5S to Schedule 40S (heavier walls on enquiry)"],
      ["Length", "Single Random, Double Random, or Fixed Cut Length"],
      ["Ends", "Plain End (PE); Bevelled End (BE); Threaded on request"],
      ["Surface Finish", "Pickled & Passivated (standard); Bright Annealed or Polished on request"],
      ["Marking", "Standard mill marking; custom marking on request"],
      ["Packaging", "Export-worthy bundling, end protection and crating"],
    ],
    dimensionsNote: "Representative welded-pipe size range. A complete chart can be requested through the product enquiry form.",
    dimensionHeaders: ["NPS", "OD (mm)", "Wall thickness (mm) — Sch 10S/40S", "Schedule"],
    dimensions: [
      ["4\"", "114.3", "3.05 / 6.02", "10S / 40S"],
      ["8\"", "219.1", "3.76 / 8.18", "10S / 40S"],
      ["12\"", "323.9", "4.57 / 9.53", "10S / 40S"],
      ["16\"", "406.4", "4.78 / 9.53", "10S / 40S"],
      ["24\"", "610.0", "6.35 / 9.53", "10S / 40S"],
      ["36\"", "914.4", "7.92 / 9.53 (project-confirmed)", "10S / project"],
    ],
    manufacturing: [
      "Material is verified, levelled and prepared to the required width for the ordered size.",
      "Strip or plate is progressively formed into a cylindrical shape.",
      "The seam is closed by the qualified welding process applicable to the ordered specification.",
      "Post-weld heat treatment, sizing and straightening are completed as the specification requires.",
      "The seam and pipe body receive the specified visual, dimensional, hydrostatic and NDT examinations.",
    ],
  },
  "EFW Pipes": {
    displayTitle: "Stainless Steel EFW Pipes",
    tagline: "Large-Diameter, Heavy-Wall EFW Pipe for Major Process Piping Projects.",
    overviewContent: [
      "NESCO Pipe & Tubes supplies electric-fusion-welded (EFW) pipes for large-diameter, heavy-wall process piping where sizes and thicknesses exceed the practical range of standard welded or seamless pipe. EFW pipe is manufactured from tested plate, rolled into a cylindrical shell and joined along a longitudinal seam by an electric fusion welding process — typically single or double submerged-arc welding — qualified to the procedure required by the governing specification. Post-weld heat treatment, sizing and straightening follow, and the seam and pipe body are examined by radiography or ultrasonic testing, along with hydrostatic testing and dimensional checks, before dispatch.",
      "Because EFW pipe is produced from individually rolled plate rather than coil, it supports diameters and wall thicknesses that seamless and standard welded processes cannot practically reach, making it a standard choice for large process headers, major pipelines, and heavy-wall pressure piping on refinery, petrochemical and power projects. The manufacturing route, weld procedure and inspection scope are project-specific and should be clearly agreed at enquiry stage, since EFW orders are generally made-to-order rather than ex-stock.",
      "Industries specify EFW pipe from NESCO Pipe & Tubes when a project requires large-diameter or heavy-wall stainless or duplex pipe with a fully documented weld procedure, heat treatment record and inspection package. NESCO reviews each EFW enquiry against the plate specification, weld procedure, heat treatment requirement, NDT scope and delivery timeline, and coordinates third-party witnessing where the project calls for it — supporting project teams from enquiry through to delivery on demanding, large-scale piping packages.",
    ],
    keyFeatures: ["Large-Diameter & Heavy-Wall Capability", "Fully Documented Weld Procedure", "Suited to Major Process Piping Projects", "Post-Weld Heat Treatment Available", "Full Radiographic / Ultrasonic Examination", "Suitable for Corrosion-Resistant & High-Alloy Materials", "Project-Specific Manufacture", "Hydrostatically Tested"],
    specificationReferences: ["ASTM A358 for austenitic stainless EFW pipe", "ASTM A928 for duplex stainless EFW pipe", "Project-specific dimensional standards", "Approved WPS and supplementary NDT clauses"],
    productSpecifications: [
      ["Product Standard", "ASTM A358 / A928 (material); project-specific dimensional standard"],
      ["Manufacturing Type", "Electric Fusion Welded (plate-rolled, single/double submerged-arc weld)"],
      ["Size Range", "14\" NPS and above, including sizes beyond standard NPS charts (project-specific)"],
      ["Wall Thickness", "Heavy wall, project-specific — confirmed against the approved drawing"],
      ["Length", "Fixed length per project drawing/BOQ; random length generally not applicable"],
      ["Ends", "Bevelled per the project's approved weld procedure specification (WPS)"],
      ["Surface Finish", "As required by project specification"],
      ["Marking", "Per project specification; customer marking as required"],
      ["Packaging", "Export-worthy, project-specific crating and handling"],
    ],
    dimensionsNote: "EFW pipe is manufactured to project-specific diameter, wall thickness and length — there is no fixed catalogue size chart. Confirm dimensions against the project drawing, WPS and applicable code (e.g. ASME B31.3) at enquiry stage. A project data sheet can be issued once requirements are confirmed.",
    dimensionHeaders: ["Sizing basis", "Diameter", "Wall thickness", "Length"],
    dimensions: [["Project drawing / BOQ", "14\" NPS and above; non-standard diameters available", "Heavy wall, confirmed against approved drawing", "Fixed project length"]],
    manufacturing: [
      "Plate is selected, tested and rolled to the required diameter, gauge and width for the ordered specification.",
      "Edges are prepared and the plate is formed into a cylindrical shell over its full length, generally in a single or limited number of longitudinal seams.",
      "The seam is closed by electric fusion welding (typically single or double submerged-arc welding), qualified to the procedure applicable to the ordered specification.",
      "Heat treatment, sizing and straightening are carried out where the specification, wall thickness or service condition requires it.",
      "The full weld seam and pipe body undergo the specified radiographic or ultrasonic examination, hydrostatic test and dimensional checks agreed for the project.",
    ],
  },
} as const;
