export type FamilyContent = {
  intro: string;
  supplyOptions: Array<readonly [string, string]>;
  applications: string[];
  rfq: string[];
};

export type SubtypeContent = {
  description: string;
  features: string[];
  standards: string[];
};

export const technicalPublishingNote = "Standards listed are common market references, not a promise that every grade, size and product form is covered by every standard. Confirm the exact material specification, dimensional standard and supplementary requirements at quotation stage.";

export const barTechnicalPublishingNote = "Chemical composition and mechanical properties follow the applicable material standard, grade, product form and supply condition, and can be provided through the applicable Mill Test Certificate. Standards shown are common references; confirm the exact specification, dimensions and supplementary requirements at quotation stage.";

export const flangeTechnicalPublishingNote = "Standards listed are common market references, not a promise that every grade, size and flange form is covered by every standard. Confirm the exact material specification, dimensional standard and supplementary requirements at quotation stage. Detailed dimensional charts, chemical composition and mechanical-property data sheets are available on request rather than published in full on this page.";

export const fittingTechnicalPublishingNote = "Butt weld fitting standards must be applied together: the material specification, manufacturing class, dimensional standard, wall requirement and weld-end preparation are separate order inputs. Confirm the exact fitting type, grade, class, size, wall, construction route and supplementary examination at quotation stage.";

export const fastenerTechnicalPublishingNote = "A material grade does not define a complete fastener. Confirm the product type, material or strength grade, dimensional standard, thread designation, length convention, compatible nuts or washers, finish, testing and marking requirements at quotation stage.";

export const familyContent: Record<string, FamilyContent> = {
  Pipes: {
    intro: "NESCO Pipe & Tubes supplies seamless, welded and electric-fusion-welded pipes for process piping, utility systems, pressure service, chemical handling, heat-resistant duties and general industrial fabrication. Each enquiry is evaluated by material grade, governing standard, nominal pipe size, schedule or wall thickness, length, end preparation, testing and certification.",
    supplyOptions: [["Size basis", "NPS / OD / ID as specified"], ["Wall basis", "Schedule, nominal wall or minimum wall"], ["Lengths", "Single random, double random or fixed cut length"], ["Ends", "Plain, bevelled, threaded or special preparation"], ["Surface", "Annealed and pickled, descaled, polished or as manufactured"], ["Testing", "Hydrostatic, pneumatic, eddy current, ultrasonic, radiographic or other agreed methods"], ["Documents", "MTC, dimensional report, NDT reports and inspection release as required"]],
    applications: ["Oil & Gas", "Petrochemical", "Chemical Processing", "Refineries", "Power Plants", "Heat Exchangers", "Marine", "Offshore", "Water Treatment", "Desalination", "Pharmaceutical", "Food Processing", "Sugar Industry", "Pulp & Paper", "Fertilizer Plants", "General Engineering"],
    rfq: ["Name and company", "Email and phone", "Product", "Material grade", "Standard", "Dimensions", "Quantity", "Delivery location", "Required test certificates", "Additional requirements", "Upload drawing / BOQ (optional)"],
  },
  Tubes: {
    intro: "Stainless steel tubes are supplied for close dimensional tolerances, controlled surface finish and demanding service conditions. NESCO coordinates seamless, welded, heat-exchanger, boiler and instrumentation tubing together with hydraulic and bright-annealed requirements where supported by the complete specification.",
    supplyOptions: [["Dimensions", "OD × wall thickness, including the required tolerance"], ["Forms", "Straight length, fixed cut length, coil, capillary or U-bend"], ["Condition", "Annealed, solution annealed, cold drawn, pilgered or as specified"], ["Surface", "Annealed and pickled, bright annealed, polished or mill finish"], ["Ends", "Square cut, deburred, capped or special preparation"], ["Testing", "Hydrostatic, pneumatic, eddy current, ultrasonic or project-specific"], ["Packing", "Sleeved or bundled, capped, boxed or export packed"], ["Certification", "MTC and agreed inspection documentation to the purchase order"]],
    applications: ["Shell-and-tube heat exchangers", "Boilers and steam generators", "Condensers and coolers", "Instrumentation and control systems", "Chemical dosing and sampling", "Hydraulic and pneumatic lines", "Food and pharmaceutical process systems", "Semiconductor and high-cleanliness systems", "Dairy and biotechnology equipment", "HVAC and refrigeration", "Automotive and general engineering"],
    rfq: ["Tube service or equipment type", "Material grade", "Seamless or welded construction", "Applicable standard and edition", "OD, wall thickness and tolerance", "Straight, U-bend or coil form", "Length, bend radius or coil geometry", "Surface finish and cleanliness", "Testing, certification and packing requirements"],
  },
  Flanges: {
    intro: "Flanges create detachable, bolted connections between pipe, valves, vessels and equipment. Correct selection requires the material grade, standard, nominal size, pressure class, facing, bore, wall schedule, dimensions and testing requirements to be defined together.",
    supplyOptions: [["Standards", "ASME B16.5, ASME B16.47 or project drawings"], ["Sizes", "NPS and bore/schedule as specified"], ["Pressure classes", "Class 150, 300, 600, 900, 1500 and 2500 where applicable"], ["Facings", "RF, FF, RTJ and special facings"], ["Finish", "Serrated or smooth facing finish as specified"], ["Marking", "Grade, heat number, size, class, standard and manufacturer identification"], ["Testing", "PMI, hardness, UT, dimensional and other approved inspections"]],
    applications: ["Process piping connections", "Pressure vessels and nozzles", "Valves, pumps and compressors", "Refineries and petrochemical plants", "Power and steam systems", "Marine and water systems", "Chemical processing equipment", "Maintenance and shutdown projects"],
    rfq: ["Flange type", "Material grade", "Standard and pressure class", "Nominal size", "Bore / matching pipe schedule", "Facing and surface finish", "Quantity", "Testing, marking and certification"],
  },
  "Butt Weld Fittings": {
    intro: "Butt weld fittings provide smooth, permanent connections for changes in direction, branch connections, diameter transitions and end closure. They are commonly supplied in seamless or welded construction and should match the connected pipe in grade, wall thickness, dimensions and service requirements.",
    supplyOptions: [["Construction", "Seamless, welded or fabricated construction, as permitted by the applicable product specification and project requirements"], ["Dimensions", "NPS, schedule and standard"], ["End preparation", "Bevelled to specified weld preparation"], ["Heat treatment", "Solution annealed or as required by material standard"], ["Surface", "Pickled/passivated, blasted, polished or mill finish"], ["Testing", "PMI, dye penetrant, radiography/UT, dimensions and other specified tests"], ["Documentation", "MTC, NDT reports, heat-treatment charts and inspection release"]],
    applications: ["Process piping", "Oil and gas facilities", "Chemical and fertiliser plants", "Power generation", "Desalination and water treatment", "Marine piping", "Food and pharmaceutical utilities", "Fabrication and maintenance"],
    rfq: ["Fitting type and angle/configuration", "Material grade", "Standard", "NPS and schedule/wall", "Seamless or welded preference", "Quantity", "Special dimensions/drawing", "Testing and documentation"],
  },
  "Sheets, Plates & Coils": {
    intro: "Flat products are used for fabrication, pressure equipment, tanks, process vessels, cladding, formed components, heat shields, shims and general engineering. Selection should define grade, product form, thickness, width, length or coil dimensions, finish, edge condition, flatness, testing and protective packing.",
    supplyOptions: [["Forms", "Sheet, plate, coil, strip, blank or profile"], ["Thickness", "Nominal thickness and tolerance"], ["Dimensions", "Width × length or coil width/ID/OD/weight"], ["Finish", "No.1, 2B, BA, No.4, hairline, mirror or project-specific"], ["Edges", "Mill, slit, sheared, deburred or machined"], ["Processing", "Cutting, slitting, levelling, bending, drilling or profiling"], ["Protection", "Paper interleave, PVC film, oiling or moisture-barrier packing"]],
    applications: ["Pressure vessels and tanks", "Heat exchangers and tube sheets", "Chemical equipment", "Food and pharmaceutical equipment", "Marine fabrication", "Architectural and decorative work", "Automotive and transport components", "General fabrication and shimming"],
    rfq: ["Product form", "Material grade", "Standard", "Thickness and tolerance", "Width/length or coil dimensions", "Finish and edge", "Processing required", "Quantity, testing and packing"],
  },
  Bars: {
    intro: "Bars provide feedstock for machining, shafts, valves, fasteners, structural components, supports, tooling and fabricated assemblies. NESCO supplies round, bright, hexagonal, square and flat bars in stainless steel and special alloys, subject to grade, size, condition and specification.",
    supplyOptions: [["Dimensions", "Diameter, across flats, side or width × thickness"], ["Condition", "Hot rolled, forged, solution annealed, cold drawn, peeled, ground or polished"], ["Length", "Random, fixed or cut pieces"], ["Tolerance", "Commercial, precision or agreed tolerance class"], ["Surface", "Black, pickled, bright, ground, polished or machined"], ["Testing", "PMI, hardness, mechanical, UT or other agreed tests"], ["Identification", "Heat-wise tagging, stamping or colour coding as agreed"]],
    applications: ["Shafts and pump components", "Valves and fittings", "Fasteners and threaded parts", "Machined components", "Chemical and marine equipment", "Industrial machinery and OEM components", "Food/pharma equipment", "General engineering and fabrication"],
    rfq: ["Bar profile", "Material grade", "Standard", "Size and tolerance", "Condition and surface", "Length / cut list", "Quantity", "Testing and certification"],
  },
  Fasteners: {
    intro: "Fasteners secure flanged joints, equipment, structures and fabricated assemblies. Material grade, strength class, temperature, corrosion environment, thread system, dimensions, coating, nut compatibility and test documentation must be considered as one bolting package.",
    supplyOptions: [["Thread system", "Metric, UNC, UNF, 8UN or specified form"], ["Dimensions", "Diameter, pitch, length and thread engagement"], ["Condition", "Solution annealed, heat treated or cold worked as specified"], ["Finish", "Plain, passivated, coated, plated or lubricated subject to compatibility"], ["Sets", "Bolt/nut/washer or stud with two nuts"], ["Testing", "Chemical, mechanical, hardness, PMI and coating tests as required"], ["Marking", "Grade, manufacturer and heat/lot identification"]],
    applications: ["Flanged piping joints", "Pressure vessels", "Valves and pumps", "Chemical and marine equipment", "Structural assemblies", "Heat exchangers", "Power plants", "Maintenance and shutdowns"],
    rfq: ["Fastener type", "Material / bolting grade", "Dimensional standard", "Thread diameter and pitch", "Length", "Nut/washer requirement", "Coating/lubrication", "Quantity and test documents"],
  },
};

export const subtypeContent: Record<string, SubtypeContent> = {
  "Seamless Pipes": { description: "Produced without a longitudinal weld seam, seamless pipe is widely selected where pressure integrity, uniformity and service reliability are critical. It is used in process lines, high-temperature systems, chemical plants, refineries, power equipment and specialised alloy piping.", features: ["Strong choice for pressure and temperature duties", "Uniform circumferential structure without a longitudinal seam", "Available in stainless, duplex, nickel-alloy, copper-nickel and titanium specifications", "Plain, bevelled or threaded ends subject to size and standard"], standards: ["ASTM A312 for austenitic stainless pipe", "ASTM A790 for duplex stainless pipe", "Material-specific ASTM B-series standards for nickel, copper-nickel and titanium", "ASME B36.19M / B36.10M dimensional references where applicable"] },
  "Welded Pipes": { description: "Welded pipe is formed from strip or plate and joined along a longitudinal seam. It provides a practical solution for a wide range of sizes, wall thicknesses and corrosion-resistant materials, especially where dimensional range and commercial efficiency are important.", features: ["Broad diameter and wall-thickness possibilities", "Suitable for process, structural, utility and fabrication requirements", "Longitudinal seam can be inspected by agreed NDT methods", "Available with pickled, annealed, polished or project-specific surface condition"], standards: ["ASTM A312 / A358 for stainless steel applications", "ASTM A790 / A928 for duplex applications", "Material-specific ASTM B-series welded-pipe specifications", "ASME dimensional standards as stated on the purchase order"] },
  "EFW Pipes": { description: "Electric Fusion Welded pipe is generally produced from plate with an electrically fused longitudinal seam and is frequently specified for larger diameters, heavier walls and demanding process-piping projects. The manufacturing route, weld procedure and inspection scope should be clearly stated in the approved specification.", features: ["Useful for large-diameter and heavy-wall requirements", "Project-specific weld examination and heat treatment options", "Suitable for corrosion-resistant and high-alloy materials", "Random or fixed lengths subject to manufacturing feasibility"], standards: ["ASTM A358 for austenitic stainless EFW pipe", "ASTM A928 for duplex stainless EFW pipe", "Applicable ASME dimensional requirements", "Project-specific supplementary testing and NDT clauses"] },
  "Seamless Tubes": { description: "Seamless tubing offers a continuous wall and is selected for pressure, heat-transfer, mechanical and critical service. It may be cold drawn or finished to achieve tighter dimensional control and surface quality.", features: ["Suitable for pressure and mechanical duties", "Good dimensional consistency when cold finished", "Wide material and heat-treatment choices", "Straight, cut-length or U-bent forms where applicable"], standards: ["ASTM A269 for general-service stainless tubing", "ASTM A213 for seamless boiler, superheater and heat-exchanger tubing", "ASTM A789 for duplex stainless tubing", "Material-specific ASTM B-series standards"] },
  "Welded Tubes": { description: "Welded tubing provides a versatile and economical format for heat-transfer, process, structural and hygienic duties. Weld condition, bead treatment, heat treatment and inspection should be selected for the intended application.", features: ["Broad production range", "Consistent OD and surface finish", "Weld bead worked or removed where specified", "Eddy-current, hydrostatic or pneumatic testing as required"], standards: ["ASTM A269 for general-service stainless tubing", "ASTM A249 for welded boiler and heat-exchanger tubes", "ASTM A789 for duplex tubing", "Applicable material-specific standards"] },
  "Heat Exchanger Tubes": { description: "Heat exchanger tubes transfer heat between fluids in shell-and-tube condensers, coolers, evaporators and process exchangers. Material selection should consider fluid chemistry, chloride exposure, velocity, temperature, fouling and cleaning method.", features: ["Straight or U-bend configurations", "Tight OD, wall and ovality control", "Cleanliness and surface condition suited to heat transfer", "Eddy current, hydrostatic, pneumatic or other inspection options"], standards: ["ASTM A213 / A249 for stainless applications", "ASTM A789 for duplex applications", "ASTM B-series standards for nickel and copper-nickel alloys", "Project-specific U-bend and heat-treatment requirements"] },
  "Boiler Tubes": { description: "Boiler tubes are used in water walls, economisers, superheaters, reheaters and steam-generating equipment. They require careful control of material condition, dimensions, heat treatment and test documentation.", features: ["Designed for temperature and pressure service", "Seamless or welded routes depending on specification", "Cut lengths and end preparation for fabrication", "Mechanical, flattening, flaring and NDT requirements as specified"], standards: ["ASTM A213 for seamless ferritic/austenitic alloy-steel boiler tubes", "ASTM A249 for welded austenitic boiler tubes", "ASME Section II material references where contractually required", "Project or OEM-specific supplementary requirements"] },
  "Instrumentation Tubes": { description: "Instrumentation tubing is used for impulse lines, analyser systems, hydraulic and pneumatic control, sampling, dosing and small-bore process connections. Reliable sealing depends on accurate OD, controlled hardness, smooth surfaces and compatible tube fittings.", features: ["Precision outside diameter and wall thickness", "Bright annealed or solution-annealed finishes where required", "Straight lengths or coils", "High-cleanliness, capped-end and special packing options"], standards: ["ASTM A269 and related material standards", "Seamless or welded/cold-worked condition as specified", "Hardness and surface requirements matched to fitting system", "Hydrostatic or pneumatic leak testing as agreed"] },
  "Weld Neck Flanges": { description: "Weld neck flanges use a tapered hub and butt-weld connection to transfer stress gradually from the flange to the pipe. They are commonly chosen for high-pressure, cyclic, high-temperature and critical process service.", features: ["Strong, fatigue-resistant connection", "Bore can be matched to pipe schedule", "Suitable for radiographic examination of butt weld", "Available in raised face, flat face and ring-type joint forms"], standards: ["ASME B16.5 for standard-size flanges", "ASME B16.47 for large-diameter flanges", "ASTM A182 for forged stainless/duplex material", "ASTM B564 / ASTM B381 for nickel-alloy and titanium forgings, respectively, where applicable"] },
  "Slip-On Flanges": { description: "Slip-on flanges slide over the pipe and are generally attached with internal and external fillet welds. They are commonly used in general, utility and process piping where installation economy and alignment flexibility are important, subject to the applicable piping design and service requirements.", features: ["Easy fit-up and alignment", "Cost-effective for many utility and process lines", "Available in multiple pressure classes and facings", "Bore and hub dimensions must suit the pipe OD"], standards: ["ASME B16.5 dimensional standard", "Applicable forged-material specification", "Project welding and inspection requirements"] },
  "Blind Flanges": { description: "Blind flanges close the end of a piping system, nozzle or valve connection. They permit future access for inspection or extension and must be selected for the full design pressure, temperature and bolting load.", features: ["Positive line closure", "No centre bore", "Useful for inspection openings and future expansion", "Thickness and facing depend on size, class and standard"], standards: ["ASME B16.5 / B16.47 as applicable", "Material specification matched to piping class", "Facing and bolt-hole requirements per project"] },
  "Socket Weld Flanges": { description: "Socket weld flanges contain a recessed socket into which the pipe is inserted before fillet welding. They are commonly used on small-bore, high-pressure piping where compact connections are desired.", features: ["Compact connection for small-bore piping", "Good alignment during installation", "Common in high-pressure utility and process services", "Requires specified expansion gap and qualified welding practice"], standards: ["ASME B16.5", "ASME B16.11 relevance for associated socket-weld fittings", "Material specification per piping class"] },
  "Threaded Flanges": { description: "Threaded flanges connect to externally threaded pipe without a circumferential weld. They can be useful where welding is restricted, but suitability must be checked carefully for pressure, temperature, vibration, cyclic loading and hazardous service.", features: ["No flange-to-pipe welding required", "Useful for selected low-pressure or special services", "Available with standard thread forms", "Service limitations should be approved by the piping engineer"], standards: ["ASME B16.5", "Thread form per specified piping standard", "Material and pressure-temperature rating per design"] },
  Elbows: { description: "Elbows change pipeline direction while maintaining a continuous flow path. Common configurations include 45°, 90° and 180° returns in long-radius or short-radius patterns.", features: ["45°, 90° and 180° configurations", "Long-radius and short-radius options", "Seamless or welded construction", "Tangents, special angles and heavy-wall designs subject to drawing"], standards: ["ASME B16.9 for factory-made butt-welding fittings", "MSS SP-43 for applicable low-pressure, corrosion-resistant light-wall fittings", "ASTM A403, A815 or material-specific ASTM B366 specifications"] },
  Tees: { description: "Tees create a 90-degree branch from the main pipeline. Equal tees retain the run diameter, while reducing tees connect a smaller branch.", features: ["Equal and reducing configurations", "Smooth branch transition", "Seamless or welded manufacture", "Special outlet sizes and barred tees subject to project specification"], standards: ["ASME B16.9", "Applicable material specification", "Project-specific branch reinforcement or flow requirements"] },
  Reducers: { description: "Reducers connect pipe of different diameters. Concentric reducers maintain a common centreline, while eccentric reducers offset the centreline to manage drainage, vapour pockets or pump-suction requirements.", features: ["Concentric and eccentric types", "Smooth diameter transition", "Schedule and end thickness matched to piping system", "Flat-side orientation defined for eccentric reducers"], standards: ["ASME B16.9", "Material specification compatible with piping class", "Dimensional and wall-thickness checks"] },
  "Stub Ends": { description: "Stub ends are used with lap-joint flanges to create a rotatable, demountable connection. They are valuable where frequent dismantling or alignment flexibility is needed, or where an economical backing flange can be used.", features: ["Type A, B or C patterns as specified", "Short or long pattern", "Lapped face mates with loose backing flange", "Useful in corrosion-resistant piping systems"], standards: ["ASME B16.9 / MSS SP-43 as applicable", "Material and lap dimensions per project", "Facing and radius matched to backing flange"] },
  "End Caps": { description: "End caps permanently close the end of a butt-weld piping run. Their geometry provides a smooth pressure boundary and they are used during construction, isolation, maintenance or final line termination.", features: ["Permanent welded closure", "Formed closure profile according to the applicable standard and design requirement", "Seamless or welded construction", "Wall thickness matched to connected pipe"], standards: ["ASME B16.9", "Applicable material specification", "Project pressure and examination requirements"] },
  Sheets: { description: "Sheets are relatively thin, flat-rolled products supplied in standard or cut sizes. They are widely used for enclosures, trays, liners, architectural details, fabricated components and corrosion-resistant equipment.", features: ["Standard and custom cut sizes", "Cold-rolled and hot-rolled conditions", "Decorative, polished or industrial finishes", "PVC/laser film protection where appropriate"], standards: ["ASTM A240 for stainless/duplex sheet and plate", "Material-specific ASTM B-series standards", "Dimensional tolerances per agreed specification"] },
  Plates: { description: "Plates provide the thickness and structural capacity required for vessels, tanks, tube sheets, flanges, supports and heavy fabrication. Heat treatment, flatness, surface condition and ultrasonic examination may be important for critical applications.", features: ["Wide range of thicknesses and dimensions", "Mill plates or cut profiles", "Solution annealed, hot rolled or descaled conditions", "UT, PMI and mechanical test options"], standards: ["ASTM A240 for stainless/duplex plate", "Material-specific nickel/copper/titanium plate standards", "Project-specific pressure-vessel or fabrication requirements"] },
  Coils: { description: "Coils support continuous processing, slitting, roll forming, stamping and high-volume fabrication. Coil requirements should state thickness, width, ID/OD, weight, finish, edge and permissible welds.", features: ["Master coils or slit coils", "Controlled width and edge condition", "Consistent finish for repeat fabrication", "Protective wrapping and eye-to-sky/eye-to-wall packing options"], standards: ["Applicable flat-product material specification", "Tolerance and coil geometry per purchase order", "Surface and edge acceptance criteria"] },
  "Shim Sheets": { description: "Shim sheets are precision thin flat products used for alignment, spacing, wear adjustment, sealing support and dimensional compensation. They may be supplied as sheets, strips, coils or cut components.", features: ["Thin gauges and close thickness control", "Full-hard, annealed or specified temper", "Sheets, strips, coils or cut shims", "Deburred edges and protective packaging"], standards: ["Grade-specific sheet/strip standard", "Thickness tolerance agreed before order", "Special flatness, hardness or spring-temper requirements"] },
  "Round Bars": { description: "Round bars are the most versatile bar form for shafts, pins, rings, machined components, fasteners and general fabrication. They are available in a wide range of diameters and sizes, subject to grade, manufacturing route, standard and availability.", features: ["Hot-rolled, forged, peeled, turned or cold-finished conditions", "Straight lengths or cut pieces", "Centreless ground or polished finishes", "UT and mechanical testing for critical applications"], standards: ["ASTM A276 / A479 for common stainless bar applications", "ASTM A484 general requirements", "Material-specific nickel, duplex, copper-nickel and titanium standards"] },
  "Bright Bars": { description: "Bright bars are precision-finished bars that may be cold drawn, peeled, turned, ground or polished to achieve improved dimensional accuracy and surface finish.", features: ["Tighter dimensional tolerance", "Improved surface quality", "Reduced initial machining allowance", "Round, hexagonal, square and special profiles"], standards: ["Material grade standard plus agreed tolerance class", "Surface and straightness requirements stated on PO", "Condition/hardness matched to machining"] },
  "Hex Bars": { description: "Hexagonal bars support the efficient production of nuts, fittings, valve parts, connectors and machined components that require wrenching flats.", features: ["Six-flat geometry for machining efficiency", "Cold-drawn or hot-finished forms", "Across-flat dimension and tolerance specified", "Cut lengths and chamfering available where confirmed"], standards: ["Applicable bar material standard", "Dimensional tolerance agreed by across-flats size"] },
  "Square Bars": { description: "Square bars are used in machine components, frames, supports, grills, architectural fabrication and general engineering.", features: ["Uniform four-sided profile", "Hot-rolled or cold-finished conditions", "Straight or cut-length supply", "Machining and fabrication friendly"], standards: ["Applicable bar material standard", "Side dimension, corner radius and tolerance specified"] },
  "Flat Bars": { description: "Flat bars offer a rectangular section for supports, brackets, frames, base plates, wear strips and machined components. They may be hot or cold rolled, or supplied by cutting or shearing from plate or strip where permitted by the specified product standard and dimensional requirements.", features: ["Rolled or plate/strip-derived routes where permitted", "Wide range of width-to-thickness combinations", "Straight lengths or cut pieces", "Edge and surface condition selected for fabrication"], standards: ["Applicable bar or plate-derived standard", "Width, thickness, edge and straightness requirements"] },
  Bolts: { description: "Industrial bolts may be supplied in hex-head, socket-head, eye, U-bolt or drawing-specific forms. For steel and alloy applications, material compatibility and mechanical properties are as important as the dimensional standard.", features: ["Metric or inch thread systems", "Coarse, fine or project-specific pitch", "Full or partial thread", "Machined, forged or cold-formed supply routes"], standards: ["ASTM F593 for selected stainless bolts", "ASTM A193 / A320 / A453 for temperature- or pressure-service bolting where applicable", "ASME, ISO, DIN or drawing dimensions"] },
  Nuts: { description: "Nuts are selected to match bolt or stud material, thread, proof load, temperature and corrosion environment. Hex, heavy hex, lock and special nuts may be supplied subject to the approved bill of materials.", features: ["Standard and heavy-hex patterns", "Matched thread fit and strength", "Plain, coated or lubricated condition", "Grade marking and heat traceability"], standards: ["ASTM F594 for selected stainless nuts", "ASTM A194 for pressure-service nuts where applicable", "ASME/ISO/DIN dimensional standards"] },
  "Stud Bolts": { description: "Stud bolts are widely used for flanged joints in piping, valves, pressure vessels and equipment. They may be fully threaded or double-ended and are commonly supplied with two compatible heavy-hex nuts.", features: ["Full-thread or double-ended forms", "Cut to specified overall length", "Matched nut sets", "Coating and lubricant options subject to service"], standards: ["ASTM A193, A320 or A453 as applicable", "ASTM A194 or compatible nut specifications", "ASME B16.5 – Applicable flange dimensions and bolting requirements for flanged joints."] },
};

export const gradeFamilyContent: Record<string, { intro: string; cta: string }> = {
  "Stainless Steel": { intro: "Stainless steels combine corrosion resistance with practical fabrication and broad product availability. Austenitic grades such as 304/304L and 316/316L are widely used across process, food, pharmaceutical and general engineering applications, while higher-alloy and heat-resistant grades serve more demanding environments.", cta: "Request stainless steel products by grade, product form, standard and size. Attach your material specification or drawing for review." },
  "Nickel Alloy": { intro: "Nickel and nickel-based alloys are selected for severe corrosion, high-temperature oxidation, reducing or oxidising chemicals, seawater and specialised process duties. Each alloy has a distinct chemistry and operating envelope; the exact UNS designation and product specification should always be stated.", cta: "Request nickel alloy products by grade, product form, standard and size. Attach your material specification or drawing for review." },
  "Duplex & Super Duplex": { intro: "Duplex stainless steels contain a mixed austenitic-ferritic structure that provides higher strength than common austenitic grades together with strong resistance to chloride stress-corrosion cracking. Super duplex grades provide enhanced resistance for severe chloride and seawater service.", cta: "Request duplex, super duplex and high-alloy stainless products by grade, product form, standard and size. Attach your material specification or drawing for review." },
  "Cupro Nickel": { intro: "Copper-nickel alloys are widely used in seawater piping, shipbuilding, offshore systems, condensers and heat exchangers because of their marine corrosion resistance, erosion behaviour and biofouling performance.", cta: "Request copper-nickel products by grade, product form, standard and size. Attach your material specification or drawing for review." },
  Titanium: { intro: "Titanium provides exceptional corrosion resistance, a high strength-to-weight ratio and reliable performance in seawater, chloride and selected chemical environments. Product cleanliness, surface condition and contamination control are important during fabrication.", cta: "Request titanium products by grade, product form, standard and size. Attach your material specification or drawing for review." },
};

export const gradeDescriptions: Record<string, string> = {
  "Stainless Steel 304 / 304L": "General-purpose austenitic stainless steel for fabrication, food equipment, architectural components and mildly corrosive service. The low-carbon L grade is commonly selected for welded fabrication.",
  "Stainless Steel 316 / 316L": "Molybdenum-bearing austenitic stainless steel with improved resistance to pitting in chloride-containing environments; widely used in chemical, marine-adjacent, pharmaceutical and process equipment.",
  "Stainless Steel 321 / 321H": "Titanium-stabilised austenitic stainless grades for elevated-temperature service. 321H uses controlled higher carbon for improved high-temperature strength.",
  "Stainless Steel 347 / 347H": "Niobium-stabilised grades used in welded and high-temperature equipment; the H version is controlled for elevated-temperature strength.",
  "Stainless Steel 309S": "Heat-resistant stainless steel used for furnace parts, heat shields and high-temperature oxidation service.",
  "Stainless Steel 310 / 310S": "High-chromium, high-nickel heat-resistant stainless steels for elevated-temperature and oxidation-resistant components.",
  "Stainless Steel 317L": "Higher-molybdenum austenitic stainless steel offering improved resistance in selected chemical and chloride environments.",
  "Stainless Steel 904L": "High-alloy austenitic stainless steel used in aggressive chemical, acid and chloride-containing services where standard 300-series grades may be insufficient.",
  "Stainless Steel 316Ti": "Titanium-stabilised 316 variant for selected welded and elevated-temperature applications.",
  "Stainless Steel 400": "A family of ferritic and martensitic stainless grades. The exact grade—such as 409, 410, 420, 430 or another designation—must be specified because properties and applications vary significantly.",
  "Alloy 20 (UNS N08020)": "Nickel-iron-chromium alloy developed for sulphuric-acid and general chemical-processing environments.",
  "Alloy 28 (UNS N08028)": "High-alloy austenitic material used in selected acid, chloride and oil-and-gas process environments.",
  "Alloy 200 / 201 (UNS N02200 / N02201)": "Commercially pure wrought nickel. Alloy 201 is the low-carbon version often preferred for higher-temperature service.",
  "Monel® 400 (UNS N04400)": "Nickel-copper alloy valued for resistance in seawater, hydrofluoric acid and several reducing environments.",
  "Inconel® 600 (UNS N06600)": "Nickel-chromium alloy with corrosion and heat resistance across furnace, chemical and thermal-processing applications.",
  "Inconel® 601 (UNS N06601)": "Nickel-chromium alloy with aluminium addition for strong oxidation resistance in high-temperature equipment.",
  "Inconel® 625 (UNS N06625)": "Nickel-chromium-molybdenum-niobium alloy combining high strength with excellent resistance to pitting, crevice corrosion and severe environments.",
  "Inconel® 718 (UNS N07718)": "Age-hardenable nickel-chromium alloy combining high strength, corrosion resistance and useful performance across demanding low- and elevated-temperature applications.",
  "Incoloy® 800 (UNS N08800)": "Iron-nickel-chromium alloy used for oxidation, carburisation and high-temperature process equipment.",
  "Incoloy® 800H / 800HT (UNS N08810 / N08811)": "Controlled-composition and heat-treated variants designed for improved creep and rupture properties at elevated temperatures.",
  "Incoloy® 825 (UNS N08825)": "Nickel-iron-chromium-molybdenum-copper alloy used for acid, sour-service and marine-related corrosion duties.",
  "Hastelloy® C22 (UNS N06022)": "Nickel-chromium-molybdenum-tungsten alloy with broad resistance in oxidising and reducing chemical environments.",
  "Hastelloy® C276 (UNS N10276)": "Versatile nickel-molybdenum-chromium alloy used in severe chemical processing, pollution control and corrosive waste treatment.",
  "Duplex 2205 (UNS S31803 / S32205)": "The most widely used duplex family, combining high strength with resistance to pitting, crevice corrosion and chloride stress-corrosion cracking.",
  "Super Duplex 2507 (UNS S32750 / S32760)": "High-alloy duplex grades for offshore, seawater, desalination, chemical and high-chloride applications.",
  "Duplex 2304 (UNS S32304)": "Lean duplex grade providing useful strength and corrosion resistance with lower alloy content for selected structural and process applications.",
  "SMO® 254 (UNS S31254)": "A super-austenitic stainless steel with high molybdenum and nitrogen content for strong resistance to pitting and crevice corrosion. It should be listed separately from duplex grades in technically precise content.",
  "CuNi 70/30 (C71500)": "Higher-nickel copper-nickel alloy selected for demanding seawater, condenser and marine service, including higher flow or turbulence conditions.",
  "CuNi 90/10 (C70600)": "Widely used marine copper-nickel alloy offering a strong balance of seawater corrosion resistance, fabrication and commercial availability.",
  "Titanium Grade 2": "Commercially pure titanium with excellent corrosion resistance, formability and weldability for chemical processing, heat exchangers, marine and general industrial service.",
  "Titanium Grade 5": "Ti-6Al-4V alloy offering high strength and low density for aerospace, high-performance engineering and demanding mechanical components.",
  "Titanium Grade 7": "Commercially pure titanium alloyed with palladium for improved corrosion resistance in selected reducing acid environments.",
};

export const gradeAvailableForms = "Client-approved product forms include pipes, tubes, flanges, butt weld fittings, sheets and plates, coils and round bars, subject to the selected grade and governing standard.";
export const materialSelectionNote = "The correct material depends on more than corrosion resistance alone. Temperature, pressure, chloride exposure, chemistry, erosion, fabrication route, weldability, mechanical strength, product form, code requirements and lifecycle cost should be reviewed together. Final grade selection remains with the customer’s qualified engineer, designer or material specialist.";
